//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwesomeDictionary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AwesomeDictionary.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Awesome Dictionary.
        /// </summary>
        public static string AboutAwesomeDictionary {
            get {
                return ResourceManager.GetString("AboutAwesomeDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About The App.
        /// </summary>
        public static string AboutTheApp {
            get {
                return ResourceManager.GetString("AboutTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi everybody. I am with you with a new app. I investigate a lot of dictionary applications in Windows Phone and i tried to make a simple app which you will like it. If you rate the app and send your thoughts to coderserdar@outlook.com, I will be so appreciated to you. With my best regards. CoderSerdar.
        /// </summary>
        public static string AboutTheAppText {
            get {
                return ResourceManager.GetString("AboutTheAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add To Favourites.
        /// </summary>
        public static string AddToFavourites {
            get {
                return ResourceManager.GetString("AddToFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Should Select At Least One Dictionary.
        /// </summary>
        public static string AtLeastOneDictionary {
            get {
                return ResourceManager.GetString("AtLeastOneDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string BackgroundColor {
            get {
                return ResourceManager.GetString("BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color Has Been Changed Successfully.
        /// </summary>
        public static string BackgroundColorChangedSuccessfully {
            get {
                return ResourceManager.GetString("BackgroundColorChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image Has Been Changed Successfully.
        /// </summary>
        public static string BackgroundImageChangedSuccessfully {
            get {
                return ResourceManager.GetString("BackgroundImageChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image Has Been Removed Successfully.
        /// </summary>
        public static string BackgroundImageRemovedSuccessfully {
            get {
                return ResourceManager.GetString("BackgroundImageRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Settings Has Been Reset Successfully.
        /// </summary>
        public static string BackgroundSettingsResetSuccessfully {
            get {
                return ResourceManager.GetString("BackgroundSettingsResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        public static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        public static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        public static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyuk Lugat (Turkish-&gt;Turkish).
        /// </summary>
        public static string BuyukLugat {
            get {
                return ResourceManager.GetString("BuyukLugat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Dictionary (English-&gt;Turkish).
        /// </summary>
        public static string ComputerDictionary {
            get {
                return ResourceManager.GetString("ComputerDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact With Us.
        /// </summary>
        public static string ContactWithUs {
            get {
                return ResourceManager.GetString("ContactWithUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionaries Have Been Installed Successfully.
        /// </summary>
        public static string DictionariesInstalledSuccessfully {
            get {
                return ResourceManager.GetString("DictionariesInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionaries Have Been Uninstalled Successfully.
        /// </summary>
        public static string DictionariesUninstalledSuccessfully {
            get {
                return ResourceManager.GetString("DictionariesUninstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dictionary Install.
        /// </summary>
        public static string DictionaryInstall {
            get {
                return ResourceManager.GetString("DictionaryInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English-&gt;Turkish Dictionary Vol. 1.
        /// </summary>
        public static string EnglishTurkishVol1 {
            get {
                return ResourceManager.GetString("EnglishTurkishVol1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English-&gt;Turkish Dictionary Vol. 2.
        /// </summary>
        public static string EnglishTurkishVol2 {
            get {
                return ResourceManager.GetString("EnglishTurkishVol2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit App.
        /// </summary>
        public static string ExitApp {
            get {
                return ResourceManager.GetString("ExitApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure To Exit The Application?.
        /// </summary>
        public static string ExitAppQuestion {
            get {
                return ResourceManager.GetString("ExitAppQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite Word Count.
        /// </summary>
        public static string FavouriteNameCount {
            get {
                return ResourceManager.GetString("FavouriteNameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        public static string FontFamily {
            get {
                return ResourceManager.GetString("FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family Has Been Changed Successfully.
        /// </summary>
        public static string FontFamilyChangedSuccessfully {
            get {
                return ResourceManager.GetString("FontFamilyChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size Has Been Changed Successfully.
        /// </summary>
        public static string FontSizeChangedSuccessfully {
            get {
                return ResourceManager.GetString("FontSizeChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Settings.
        /// </summary>
        public static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string German {
            get {
                return ResourceManager.GetString("German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German-&gt;Turkish Dictionary.
        /// </summary>
        public static string GermanTurkish {
            get {
                return ResourceManager.GetString("GermanTurkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        public static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may restart the application for changes will be effect..
        /// </summary>
        public static string LanguageWarning {
            get {
                return ResourceManager.GetString("LanguageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning.
        /// </summary>
        public static string Meaning {
            get {
                return ResourceManager.GetString("Meaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favourites.
        /// </summary>
        public static string MyFavourites {
            get {
                return ResourceManager.GetString("MyFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        public static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oxford (English-&gt;English).
        /// </summary>
        public static string OxfordDictionary {
            get {
                return ResourceManager.GetString("OxfordDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        public static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random 10 Words.
        /// </summary>
        public static string RandomWords {
            get {
                return ResourceManager.GetString("RandomWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Background Image.
        /// </summary>
        public static string RemoveBackgroundImage {
            get {
                return ResourceManager.GetString("RemoveBackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Favourites.
        /// </summary>
        public static string RemoveFromFavourite {
            get {
                return ResourceManager.GetString("RemoveFromFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Will Remove The Word From Favourites. Are You Sure?.
        /// </summary>
        public static string RemoveFromFavouriteQuestion {
            get {
                return ResourceManager.GetString("RemoveFromFavouriteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove From Favourites.
        /// </summary>
        public static string RemoveFromFavourites {
            get {
                return ResourceManager.GetString("RemoveFromFavourites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string ResetSettings {
            get {
                return ResourceManager.GetString("ResetSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risale Nur (Turkish-&gt;Turkish).
        /// </summary>
        public static string RisaleNur {
            get {
                return ResourceManager.GetString("RisaleNur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Completed.
        /// </summary>
        public static string SearchCompleted {
            get {
                return ResourceManager.GetString("SearchCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search In Meanings.
        /// </summary>
        public static string SearchInMeanings {
            get {
                return ResourceManager.GetString("SearchInMeanings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Criteria Can Not Be Empty.
        /// </summary>
        public static string SearchTrimFault {
            get {
                return ResourceManager.GetString("SearchTrimFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Background Color.
        /// </summary>
        public static string SelectBackgroundColor {
            get {
                return ResourceManager.GetString("SelectBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Font Family.
        /// </summary>
        public static string SelectFontFamily {
            get {
                return ResourceManager.GetString("SelectFontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Font Size.
        /// </summary>
        public static string SelectFontSize {
            get {
                return ResourceManager.GetString("SelectFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send With Awesome Dictionary App.
        /// </summary>
        public static string SendWithAwesomeDictionaryApp {
            get {
                return ResourceManager.GetString("SendWithAwesomeDictionaryApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send With E-Mail.
        /// </summary>
        public static string SendWithEmail {
            get {
                return ResourceManager.GetString("SendWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send With SMS.
        /// </summary>
        public static string SendWithSMS {
            get {
                return ResourceManager.GetString("SendWithSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronizing.
        /// </summary>
        public static string Synchronizing {
            get {
                return ResourceManager.GetString("Synchronizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Has A Fault. Please Try Again Later..
        /// </summary>
        public static string SystemFault {
            get {
                return ResourceManager.GetString("SystemFault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Word Count.
        /// </summary>
        public static string TotalNameCount {
            get {
                return ResourceManager.GetString("TotalNameCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        public static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Has Been Added To Favourites Successfully.
        /// </summary>
        public static string WordAddedFavouriteSuccessfully {
            get {
                return ResourceManager.GetString("WordAddedFavouriteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Is Already Favourite.
        /// </summary>
        public static string WordAlreadyFavourite {
            get {
                return ResourceManager.GetString("WordAlreadyFavourite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word And Meaning.
        /// </summary>
        public static string WordAndMeaning {
            get {
                return ResourceManager.GetString("WordAndMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Meaning Dictionary.
        /// </summary>
        public static string WordMeaning {
            get {
                return ResourceManager.GetString("WordMeaning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word Has Been Removed From Favourites Successfully.
        /// </summary>
        public static string WordRemovedFavouriteSuccessfully {
            get {
                return ResourceManager.GetString("WordRemovedFavouriteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
